# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - cd Code/Documentation
  - doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  local_dir: Code/Documentation/html
  skip_cleanup: true
  token: $GITHUB_TOKEN
  on:
    branch: master
