//============================================================================
//
// This file is part of the Thea project.
//
// This software is covered by the following BSD license, except for portions
// derived from other works which are covered by their respective licenses.
// For full licensing information including reproduction of these external
// licenses, see the file LICENSE.txt provided in the documentation.
//
// Copyright (C) 2019, Siddhartha Chaudhuri
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// * Neither the name of the copyright holders nor the names of contributors
// to this software may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
//============================================================================

//============================================================================
//
// ORIGINAL LICENSE
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
//============================================================================

#ifndef __Thea_ThreadGroup_hpp__
#define __Thea_ThreadGroup_hpp__

#include "Common.hpp"
#include "Array.hpp"
#include "List.hpp"
#include <boost/thread/lock_guard.hpp>
#include <boost/thread/locks.hpp>
#include <boost/thread/shared_mutex.hpp>
#include <algorithm>
#include <thread>

namespace Thea {

/**
 * Manages a group of threads and allows waiting for all of them to finish. Exists because <code>boost::thread_group</code> did
 * not make it to C++11. Lifted straight from the Boost source code (1.67.0).
 */
class THEA_API ThreadGroup
{
  private:
    /** Disable copy construction. */
    ThreadGroup(ThreadGroup const &);

    /** Disable assignment. */
    ThreadGroup & operator=(ThreadGroup const &);

  public:
    /** Default constructor. */
    ThreadGroup() {}

    /** Destructor. */
    ~ThreadGroup()
    {
      for (TheaList<std::thread *>::iterator it = threads.begin(), end = threads.end(); it != end; ++it)
        delete *it;
    }

    /** Check if the group contains the current thread. */
    bool containsThisThread() const
    {
      std::thread::id id = std::this_thread::get_id();
      boost::shared_lock<boost::shared_mutex> guard(m);

      for (TheaList<std::thread *>::const_iterator it = threads.begin(), end = threads.end(); it != end; ++it)
      {
        if ((*it)->get_id() == id)
          return true;
      }

      return false;
    }

    /** Check if the group contains a particular thread. */
    bool containsThread(std::thread * thrd) const
    {
      if (thrd)
      {
        std::thread::id id = thrd->get_id();
        boost::shared_lock<boost::shared_mutex> guard(m);

        for (TheaList<std::thread*>::const_iterator it = threads.begin(), end = threads.end(); it != end; ++it)
        {
          if ((*it)->get_id() == id)
            return true;
        }
      }

      return false;
    }

    /** Create a thread wrapping a functor and add it to the group. */
    template <typename F> std::thread * createThread(F thread_func)
    {
      boost::lock_guard<boost::shared_mutex> guard(m);
      std::unique_ptr<std::thread> new_thread(new std::thread(thread_func));
      threads.push_back(new_thread.get());
      return new_thread.release();
    }

    /** Add an existing thread to the group. */
    void addThread(std::thread * thrd)
    {
      if (thrd)
      {
        alwaysAssertM(!containsThread(thrd), "ThreadGroup: Thread is already in group");

        boost::lock_guard<boost::shared_mutex> guard(m);
        threads.push_back(thrd);
      }
    }

    /** Remove a thread from the group. */
    void removeThread(std::thread * thrd)
    {
      boost::lock_guard<boost::shared_mutex> guard(m);

      TheaList<std::thread *>::iterator const it = std::find(threads.begin(), threads.end(), thrd);
      if (it != threads.end())
        threads.erase(it);
    }

    /** Wait for all threads to finish. */
    void joinAll()
    {
      alwaysAssertM(!containsThisThread(), "ThreadGroup: Can't join the executing thread");
      boost::shared_lock<boost::shared_mutex> guard(m);

      for (TheaList<std::thread *>::iterator it = threads.begin(), end = threads.end(); it != end; ++it)
      {
        if ((*it)->joinable())
          (*it)->join();
      }
    }

    size_t numThreads() const
    {
      boost::shared_lock<boost::shared_mutex> guard(m);
      return threads.size();
    }

  private:
    TheaList<std::thread *> threads;  // Holds the set of threads.
    mutable boost::shared_mutex m;    // Mutex allowing multiple-reader/single-writer access to the thread list.

}; // class ThreadGroup

} // namespace Thea

#endif
